### ISSUE TITLE
Can't send with string instead of view

### ISSUE THREAD

**Issue by bendparker** [SimpleSoftwareIO/simple-sms#31]
I get this message:

InvalidArgumentException in FileViewFinder.php line 137:
View [This is a test!] not found.

**Comment by SimplyCorey** [comment]
Are you using the email driver?

**Comment by bendparker** [comment]
Yep...is that not supported?  I apologize if I missed something in the docs.

**Comment by SimplyCorey** [comment]
It is supported, but a known bug exists.  I plan on cleaning up these bug reports this weekend and releasing the next version.  More than likely, this will be ready to go on Sunday. Sorry for the issues.

**Comment by bendparker** [comment]
No worries, I appreciate the repository.  I'll try again when I see the next version released.

**Comment by bendparker** [comment]
Any progress on this?

**Comment by SimplyCorey** [comment]
There has not been much movement.  I have been very busy on some other tasks.  The issue lies here: https://github.com/SimpleSoftwareIO/simple-sms/blob/develop/src/SimpleSoftwareIO/SMS/Drivers/EmailSMS.php#L37 

It needs to support Laravels raw method when a view is not being passed in.

Using a view is currently working with the Email driver.  As a work around for now, you could pass in a view.

**Comment by SimplyCorey** [comment]
This is fixed in the develop branch if you want to go ahead and start using it.  I plan on releasing the v3.0.0 beta this week which includes quite a few changes to the package.

**Comment by bendparker** [comment]
Thanks!  I'll wait for the v3 to be pushed out so I don't have to change settings on my composer file.
