### ISSUE TITLE
SMS::Pretend

### ISSUE THREAD

**Issue by LTSTech** [SimpleSoftwareIO/simple-sms#32]
Hello,

first thanks for this very cool library.
we hit an issue when trying to use the pretend function.
The doc says to call it statically but the definition is not static.
As a result we get an exception.

```
SMS::Pretend
Non-static method SimpleSoftwareIO\SMS\SMS::pretend() should not be called statically
```

Should the doc be updated?

Cheers!

**Comment by SimplyCorey** [comment]
@LTSTech It look like you are accessing the package the wrong way.  Are you using Laravel?  The package should never be accessed via statics.  It should be using Laravel's facades (which look like statics)  This error leads me to believe that you did not do this part of the installation.

```
Aliases

Add 'SMS' => SimpleSoftwareIO\SMS\Facades\SMS::class in your config/app.php configuration file within the aliases array.
```

Please let me know if this fixes/doesn't fix your issue.

**Comment by abulanon** [comment]
@SimplyCorey, 
It works now. 
hi added already the providers and aliases correctly to config/app.php file.

I found out that the issue is the class that I have declared in uses clause.
before: 
use SimpleSoftwareIO\SMS\SMS;
after(correct one):
use SimpleSoftwareIO\SMS\Facades\SMS;

Anyways it is ok now. Thank you for the response.

Regards..
