### ISSUE TITLE
How to add new carrier without changing EmailSMS.php file?

### ISSUE THREAD

**Issue by larryu** [SimpleSoftwareIO/simple-sms#66]
I want to add a new carrier, if I don't add it to the EmailSMS.php, I got error of "Carrier specified is not found." I think it is not a good way to change vendor file, is there any way to let the user configure the carrier via config file? Thanks.

**Comment by MelonSmasher** [comment]
If you know the carrier's information you could submit a pull request here so everyone could have those settings.

**Comment by SimplyThomas** [comment]
If you are looking to permanently add a carrier to the package, in order to contribute to the community as a whole, the best way to do it would be to add it to the EmailSMS.php file and create a pull request (don't forget to add it to the docs!) so we can review the addition and merge it in.

It's outside the scope of the project for us to create a config file to add a one-off carrier.
