### ISSUE TITLE
Laravel 5.3 error `FatalThrowableError Call to undefined method SimpleSoftwareIO\SMS\SMSServiceProvider::send()`

### ISSUE THREAD

**Issue by nanadjei** [SimpleSoftwareIO/simple-sms#76]
Trying to send message using this package and twilio but I keep getting this error `FatalThrowableError
Call to undefined method SimpleSoftwareIO\SMS\SMSServiceProvider::send()`

Thank you.

**Comment by SimplyCorey** [comment]
What does your code look like?

**Comment by nanadjei** [comment]
Am getting this new error `Call to undefined method Illuminate\Foundation\Application::share()` am using laravel 5.3

**Comment by SimplyThomas** [comment]
We need to have more context in order to help you. Can you share with us the code that you are using to call the SMS Send method? 

The `Call to undefined method Illuminate\Foundation\Application::share()` might be unrelated entirely, though it is hard to say without seeing any of your code. We need more context in order to assist you.
